version: "3.8"

services:
  api:
    build:
      context: .
    image: abdulin1982/skypro_abdulin_app
    ports:
      - 8085:80
    volumes:
      - ./docker_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    image: abdulin1982/skypro_abdulin_app
    volumes:
      - ./docker_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: welcome1
      POSTGRES_DB: flask_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flask_app -d POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
